[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/dist"

[context.production.environment]
  VITE_API_URL = "https://husums.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
